// This file is auto-generated by @hey-api/openapi-ts

export const AgentTraceEntrySchema = {
    additionalProperties: false,
    properties: {
        agent: {
            title: 'Agent',
            type: 'string'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        status: {
            title: 'Status',
            type: 'string'
        },
        summary: {
            title: 'Summary',
            type: 'string'
        }
    },
    required: [
        'agent',
        'status',
        'summary'
    ],
    title: 'AgentTraceEntry',
    type: 'object'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            title: 'Detail',
            type: 'array'
        }
    },
    title: 'HTTPValidationError',
    type: 'object'
} as const;

export const HealthResponseSchema = {
    additionalProperties: false,
    properties: {
        environment: {
            title: 'Environment',
            type: 'string'
        },
        openai_enabled: {
            title: 'Openai Enabled',
            type: 'boolean'
        },
        openai_model: {
            title: 'Openai Model',
            type: 'string'
        },
        phoenix_enabled: {
            title: 'Phoenix Enabled',
            type: 'boolean'
        },
        phoenix_project_name: {
            title: 'Phoenix Project Name',
            type: 'string'
        },
        service: {
            title: 'Service',
            type: 'string'
        },
        status: {
            title: 'Status',
            type: 'string'
        }
    },
    required: [
        'status',
        'service',
        'environment',
        'phoenix_enabled',
        'phoenix_project_name',
        'openai_enabled',
        'openai_model'
    ],
    title: 'HealthResponse',
    type: 'object'
} as const;

export const PS3LinkedEvidenceViewSchema = {
    additionalProperties: false,
    properties: {
        collection_date: {
            title: 'Collection Date',
            type: 'string'
        },
        confidence_score: {
            title: 'Confidence Score',
            type: 'number'
        },
        evidence_id: {
            title: 'Evidence Id',
            type: 'string'
        },
        flags: {
            items: {
                type: 'string'
            },
            title: 'Flags',
            type: 'array'
        },
        framework: {
            title: 'Framework',
            type: 'string'
        },
        freshness_days: {
            title: 'Freshness Days',
            type: 'integer'
        },
        link_confidence: {
            title: 'Link Confidence',
            type: 'number'
        },
        status: {
            default: '',
            title: 'Status',
            type: 'string'
        },
        type: {
            title: 'Type',
            type: 'string'
        }
    },
    required: [
        'evidence_id',
        'type',
        'framework',
        'collection_date',
        'freshness_days',
        'confidence_score',
        'link_confidence'
    ],
    title: 'PS3LinkedEvidenceView',
    type: 'object'
} as const;

export const PS3ReportResponseSchema = {
    additionalProperties: false,
    properties: {
        agent_trace: {
            items: {
                $ref: '#/components/schemas/AgentTraceEntry'
            },
            title: 'Agent Trace',
            type: 'array'
        },
        disclaimer: {
            default: '',
            title: 'Disclaimer',
            type: 'string'
        },
        generated_at: {
            title: 'Generated At',
            type: 'string'
        },
        orphan_evidence_ids: {
            items: {
                type: 'string'
            },
            title: 'Orphan Evidence Ids',
            type: 'array'
        },
        request_id: {
            title: 'Request Id',
            type: 'string'
        },
        requirements: {
            items: {
                $ref: '#/components/schemas/RequirementReport'
            },
            title: 'Requirements',
            type: 'array'
        },
        summary: {
            $ref: '#/components/schemas/PS3Summary'
        }
    },
    required: [
        'request_id',
        'generated_at',
        'summary'
    ],
    title: 'PS3ReportResponse',
    type: 'object'
} as const;

export const PS3SummarySchema = {
    additionalProperties: false,
    properties: {
        auto_collected_pct: {
            title: 'Auto Collected Pct',
            type: 'number'
        },
        compliant_count: {
            title: 'Compliant Count',
            type: 'integer'
        },
        coverage_pct: {
            title: 'Coverage Pct',
            type: 'number'
        },
        exec_summary: {
            default: '',
            title: 'Exec Summary',
            type: 'string'
        },
        frameworks: {
            items: {
                type: 'string'
            },
            title: 'Frameworks',
            type: 'array'
        },
        freshness_pct: {
            title: 'Freshness Pct',
            type: 'number'
        },
        gap_count: {
            title: 'Gap Count',
            type: 'integer'
        },
        linked_evidence_count: {
            title: 'Linked Evidence Count',
            type: 'integer'
        },
        orphan_count: {
            title: 'Orphan Count',
            type: 'integer'
        },
        overall_compliance_pct: {
            title: 'Overall Compliance Pct',
            type: 'number'
        },
        partial_count: {
            title: 'Partial Count',
            type: 'integer'
        },
        total_evidence: {
            title: 'Total Evidence',
            type: 'integer'
        },
        total_requirements: {
            title: 'Total Requirements',
            type: 'integer'
        }
    },
    required: [
        'total_requirements',
        'compliant_count',
        'partial_count',
        'gap_count',
        'overall_compliance_pct',
        'coverage_pct',
        'freshness_pct',
        'total_evidence',
        'linked_evidence_count',
        'orphan_count',
        'auto_collected_pct'
    ],
    title: 'PS3Summary',
    type: 'object'
} as const;

export const RequirementSchema = {
    additionalProperties: false,
    properties: {
        audit_frequency: {
            default: '',
            title: 'Audit Frequency',
            type: 'string'
        },
        compliance_mapping_raw: {
            default: '',
            title: 'Compliance Mapping Raw',
            type: 'string'
        },
        evidence_source: {
            default: '',
            title: 'Evidence Source',
            type: 'string'
        },
        frameworks: {
            items: {
                type: 'string'
            },
            title: 'Frameworks',
            type: 'array'
        },
        freshness_sla_days: {
            default: 90,
            title: 'Freshness Sla Days',
            type: 'integer'
        },
        id: {
            title: 'Id',
            type: 'string'
        },
        policy_id: {
            title: 'Policy Id',
            type: 'string'
        },
        policy_name: {
            title: 'Policy Name',
            type: 'string'
        },
        raw_text: {
            title: 'Raw Text',
            type: 'string'
        },
        responsible: {
            default: '',
            title: 'Responsible',
            type: 'string'
        },
        scope: {
            default: '',
            title: 'Scope',
            type: 'string'
        },
        text: {
            title: 'Text',
            type: 'string'
        }
    },
    required: [
        'id',
        'policy_id',
        'policy_name',
        'text',
        'raw_text'
    ],
    title: 'Requirement',
    type: 'object'
} as const;

export const RequirementCatalogResponseSchema = {
    additionalProperties: false,
    properties: {
        count: {
            title: 'Count',
            type: 'integer'
        },
        requirements: {
            items: {
                $ref: '#/components/schemas/Requirement'
            },
            title: 'Requirements',
            type: 'array'
        },
        source: {
            title: 'Source',
            type: 'string'
        }
    },
    required: [
        'source',
        'count'
    ],
    title: 'RequirementCatalogResponse',
    type: 'object'
} as const;

export const RequirementReportSchema = {
    additionalProperties: false,
    properties: {
        audit_frequency: {
            default: '',
            title: 'Audit Frequency',
            type: 'string'
        },
        confidence: {
            title: 'Confidence',
            type: 'number'
        },
        confidence_rationale: {
            default: '',
            title: 'Confidence Rationale',
            type: 'string'
        },
        frameworks: {
            items: {
                type: 'string'
            },
            title: 'Frameworks',
            type: 'array'
        },
        freshness_sla_days: {
            title: 'Freshness Sla Days',
            type: 'integer'
        },
        gaps: {
            items: {
                type: 'string'
            },
            title: 'Gaps',
            type: 'array'
        },
        id: {
            title: 'Id',
            type: 'string'
        },
        linked_evidence: {
            items: {
                $ref: '#/components/schemas/PS3LinkedEvidenceView'
            },
            title: 'Linked Evidence',
            type: 'array'
        },
        name: {
            title: 'Name',
            type: 'string'
        },
        narrative: {
            default: '',
            title: 'Narrative',
            type: 'string'
        },
        next_review_date: {
            default: '',
            title: 'Next Review Date',
            type: 'string'
        },
        policy_id: {
            title: 'Policy Id',
            type: 'string'
        },
        status: {
            title: 'Status',
            type: 'string'
        },
        text: {
            title: 'Text',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'text',
        'policy_id',
        'status',
        'confidence',
        'freshness_sla_days'
    ],
    title: 'RequirementReport',
    type: 'object'
} as const;

export const ValidationErrorSchema = {
    properties: {
        ctx: {
            title: 'Context',
            type: 'object'
        },
        input: {
            title: 'Input'
        },
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            title: 'Location',
            type: 'array'
        },
        msg: {
            title: 'Message',
            type: 'string'
        },
        type: {
            title: 'Error Type',
            type: 'string'
        }
    },
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError',
    type: 'object'
} as const;
