// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AnalyzeEvidenceData, AnalyzeEvidenceErrors, AnalyzeEvidenceResponses, AnalyzePs3Data, AnalyzePs3Responses, GetControlGoverningRulesData, GetControlGoverningRulesErrors, GetControlGoverningRulesResponses, GetControlRegulatoryContextData, GetControlRegulatoryContextErrors, GetControlRegulatoryContextResponses, GetControlsData, GetControlsResponses, GetDemoGoldenData, GetDemoGoldenResponses, GetHealthData, GetHealthResponses, GetKnowledgeGraphStatsData, GetKnowledgeGraphStatsResponses, GetPs3ReportPdfData, GetPs3ReportPdfResponses, GetPs3RequirementData, GetPs3RequirementErrors, GetPs3RequirementResponses, GetPs3RequirementsData, GetPs3RequirementsResponses, GetRulesByPriorityData, GetRulesByPriorityErrors, GetRulesByPriorityResponses, SearchRulesData, SearchRulesErrors, SearchRulesResponses, StreamAnalyzeEvidenceData, StreamAnalyzeEvidenceErrors, StreamAnalyzeEvidenceResponses, StreamDemoGoldenData, StreamDemoGoldenResponses, StreamPs3AnalyzeData, StreamPs3AnalyzeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Analyze uploaded compliance evidence
 */
export const analyzeEvidence = <ThrowOnError extends boolean = false>(options: Options<AnalyzeEvidenceData, ThrowOnError>) => (options.client ?? client).post<AnalyzeEvidenceResponses, AnalyzeEvidenceErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/analyze',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Stream uploaded compliance evidence analysis progress
 */
export const streamAnalyzeEvidence = <ThrowOnError extends boolean = false>(options: Options<StreamAnalyzeEvidenceData, ThrowOnError>) => (options.client ?? client).post<StreamAnalyzeEvidenceResponses, StreamAnalyzeEvidenceErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/analyze/stream',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get compliance control catalog
 */
export const getControls = <ThrowOnError extends boolean = false>(options?: Options<GetControlsData, ThrowOnError>) => (options?.client ?? client).get<GetControlsResponses, unknown, ThrowOnError>({ url: '/controls', ...options });

/**
 * Get deterministic demo analysis
 */
export const getDemoGolden = <ThrowOnError extends boolean = false>(options?: Options<GetDemoGoldenData, ThrowOnError>) => (options?.client ?? client).get<GetDemoGoldenResponses, unknown, ThrowOnError>({ url: '/demo/golden', ...options });

/**
 * Stream deterministic demo analysis progress
 */
export const streamDemoGolden = <ThrowOnError extends boolean = false>(options?: Options<StreamDemoGoldenData, ThrowOnError>) => (options?.client ?? client).get<StreamDemoGoldenResponses, unknown, ThrowOnError>({ url: '/demo/golden/stream', ...options });

/**
 * Get backend health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get full regulatory context for a control
 */
export const getControlRegulatoryContext = <ThrowOnError extends boolean = false>(options: Options<GetControlRegulatoryContextData, ThrowOnError>) => (options.client ?? client).get<GetControlRegulatoryContextResponses, GetControlRegulatoryContextErrors, ThrowOnError>({ url: '/knowledge/context/{control_id}', ...options });

/**
 * Get all rules at a given priority level
 */
export const getRulesByPriority = <ThrowOnError extends boolean = false>(options: Options<GetRulesByPriorityData, ThrowOnError>) => (options.client ?? client).get<GetRulesByPriorityResponses, GetRulesByPriorityErrors, ThrowOnError>({ url: '/knowledge/priority/{priority}', ...options });

/**
 * Get governing rules for a control from official regulatory sources
 */
export const getControlGoverningRules = <ThrowOnError extends boolean = false>(options: Options<GetControlGoverningRulesData, ThrowOnError>) => (options.client ?? client).get<GetControlGoverningRulesResponses, GetControlGoverningRulesErrors, ThrowOnError>({ url: '/knowledge/rules/{control_id}', ...options });

/**
 * Full-text search across regulatory rule text
 */
export const searchRules = <ThrowOnError extends boolean = false>(options: Options<SearchRulesData, ThrowOnError>) => (options.client ?? client).get<SearchRulesResponses, SearchRulesErrors, ThrowOnError>({ url: '/knowledge/search', ...options });

/**
 * Get knowledge graph node and relationship counts
 */
export const getKnowledgeGraphStats = <ThrowOnError extends boolean = false>(options?: Options<GetKnowledgeGraphStatsData, ThrowOnError>) => (options?.client ?? client).get<GetKnowledgeGraphStatsResponses, unknown, ThrowOnError>({ url: '/knowledge/stats', ...options });

/**
 * Run the full PS3 compliance analysis (collect -> link -> evaluate -> report)
 */
export const analyzePs3 = <ThrowOnError extends boolean = false>(options?: Options<AnalyzePs3Data, ThrowOnError>) => (options?.client ?? client).post<AnalyzePs3Responses, unknown, ThrowOnError>({ url: '/ps3/analyze', ...options });

/**
 * Stream PS3 compliance analysis progress (SSE)
 */
export const streamPs3Analyze = <ThrowOnError extends boolean = false>(options?: Options<StreamPs3AnalyzeData, ThrowOnError>) => (options?.client ?? client).get<StreamPs3AnalyzeResponses, unknown, ThrowOnError>({ url: '/ps3/analyze/stream', ...options });

/**
 * Download the PS3 audit report as PDF
 */
export const getPs3ReportPdf = <ThrowOnError extends boolean = false>(options?: Options<GetPs3ReportPdfData, ThrowOnError>) => (options?.client ?? client).get<GetPs3ReportPdfResponses, unknown, ThrowOnError>({ url: '/ps3/report.pdf', ...options });

/**
 * Get parsed policy requirements
 */
export const getPs3Requirements = <ThrowOnError extends boolean = false>(options?: Options<GetPs3RequirementsData, ThrowOnError>) => (options?.client ?? client).get<GetPs3RequirementsResponses, unknown, ThrowOnError>({ url: '/ps3/requirements', ...options });

/**
 * Get a single parsed requirement by minted id
 */
export const getPs3Requirement = <ThrowOnError extends boolean = false>(options: Options<GetPs3RequirementData, ThrowOnError>) => (options.client ?? client).get<GetPs3RequirementResponses, GetPs3RequirementErrors, ThrowOnError>({ url: '/ps3/requirements/{requirement_id}', ...options });
