// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AnalyzePs3Data, AnalyzePs3Responses, GetHealthData, GetHealthResponses, GetPs3ReportPdfData, GetPs3ReportPdfResponses, GetPs3RequirementData, GetPs3RequirementErrors, GetPs3RequirementResponses, GetPs3RequirementsData, GetPs3RequirementsResponses, StreamPs3AnalyzeData, StreamPs3AnalyzeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get backend health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Run the full PS3 compliance analysis (collect -> link -> evaluate -> report)
 */
export const analyzePs3 = <ThrowOnError extends boolean = false>(options?: Options<AnalyzePs3Data, ThrowOnError>) => (options?.client ?? client).post<AnalyzePs3Responses, unknown, ThrowOnError>({ url: '/ps3/analyze', ...options });

/**
 * Stream PS3 compliance analysis progress (SSE)
 */
export const streamPs3Analyze = <ThrowOnError extends boolean = false>(options?: Options<StreamPs3AnalyzeData, ThrowOnError>) => (options?.client ?? client).get<StreamPs3AnalyzeResponses, unknown, ThrowOnError>({ url: '/ps3/analyze/stream', ...options });

/**
 * Download the PS3 audit report as PDF
 */
export const getPs3ReportPdf = <ThrowOnError extends boolean = false>(options?: Options<GetPs3ReportPdfData, ThrowOnError>) => (options?.client ?? client).get<GetPs3ReportPdfResponses, unknown, ThrowOnError>({ url: '/ps3/report.pdf', ...options });

/**
 * Get parsed policy requirements
 */
export const getPs3Requirements = <ThrowOnError extends boolean = false>(options?: Options<GetPs3RequirementsData, ThrowOnError>) => (options?.client ?? client).get<GetPs3RequirementsResponses, unknown, ThrowOnError>({ url: '/ps3/requirements', ...options });

/**
 * Get a single parsed requirement by minted id
 */
export const getPs3Requirement = <ThrowOnError extends boolean = false>(options: Options<GetPs3RequirementData, ThrowOnError>) => (options.client ?? client).get<GetPs3RequirementResponses, GetPs3RequirementErrors, ThrowOnError>({ url: '/ps3/requirements/{requirement_id}', ...options });
