// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AgentTraceEntry
 */
export type AgentTraceEntry = {
    /**
     * Agent
     */
    agent: string;
    /**
     * Status
     */
    status: string;
    /**
     * Summary
     */
    summary: string;
};

/**
 * AnalysisResponse
 */
export type AnalysisResponse = {
    /**
     * Agent Trace
     */
    agent_trace: Array<AgentTraceEntry>;
    /**
     * Artifacts
     */
    artifacts: Array<EvidenceArtifact>;
    /**
     * Controls
     */
    controls: Array<ControlReportResult>;
    /**
     * Disclaimer
     */
    disclaimer: string;
    /**
     * Request Id
     */
    request_id: string;
    summary: AnalysisSummary;
    /**
     * Uploaded Filename
     */
    uploaded_filename: string;
};

/**
 * AnalysisSummary
 */
export type AnalysisSummary = {
    /**
     * Needs Prep Count
     */
    needs_prep_count: number;
    /**
     * Partial Count
     */
    partial_count: number;
    /**
     * Ready Count
     */
    ready_count: number;
    /**
     * Top Auditor Questions
     */
    top_auditor_questions: Array<string>;
    /**
     * Total Controls
     */
    total_controls: number;
    /**
     * Total Gap Count
     */
    total_gap_count: number;
};

/**
 * ApiErrorDetail
 */
export type ApiErrorDetail = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
};

/**
 * Body_analyzeEvidence
 */
export type BodyAnalyzeEvidence = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_streamAnalyzeEvidence
 */
export type BodyStreamAnalyzeEvidence = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ComplianceScores
 */
export type ComplianceScores = {
    /**
     * Compliance Effort
     */
    compliance_effort?: number;
    /**
     * Letter Of Law
     */
    letter_of_law?: number;
    /**
     * Spirit Of Law
     */
    spirit_of_law?: number;
};

/**
 * ControlCatalogResponse
 */
export type ControlCatalogResponse = {
    /**
     * Controls
     */
    controls: Array<ControlRequirement>;
    /**
     * Count
     */
    count: number;
    /**
     * Source
     */
    source: string;
};

/**
 * ControlEvidenceFound
 */
export type ControlEvidenceFound = {
    /**
     * Artifact
     */
    artifact: string;
    /**
     * Claim
     */
    claim: string;
    /**
     * Hash
     */
    hash: string;
    /**
     * Location
     */
    location: string;
};

/**
 * ControlReportResult
 */
export type ControlReportResult = {
    /**
     * Agent Plan
     */
    agent_plan: Array<string>;
    /**
     * Artifact
     */
    artifact: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Confidence Rationale
     */
    confidence_rationale: string;
    /**
     * Evidence Found
     */
    evidence_found: Array<ControlEvidenceFound>;
    /**
     * Gaps
     */
    gaps: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Llm Reasoning
     */
    llm_reasoning?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Priority
     */
    priority: string;
    /**
     * Provenance
     */
    provenance: string;
    /**
     * Reasoning
     */
    reasoning: Array<string>;
    /**
     * Regulation Story
     */
    regulation_story: string;
    /**
     * Regulatory Citations
     */
    regulatory_citations?: Array<string>;
    /**
     * Reviewer Question
     */
    reviewer_question: string;
    /**
     * Risk Summary
     */
    risk_summary: string;
    scores?: ComplianceScores;
    /**
     * Status
     */
    status: string;
    /**
     * Suggestion
     */
    suggestion: string;
    /**
     * Tool Trace
     */
    tool_trace: Array<ToolTraceEntry>;
};

/**
 * ControlRequirement
 */
export type ControlRequirement = {
    /**
     * Common Reviewer Questions
     */
    common_reviewer_questions: Array<string>;
    /**
     * Demo Status Target
     */
    demo_status_target: string;
    /**
     * Id
     */
    id: string;
    /**
     * Mission
     */
    mission: string;
    /**
     * Name
     */
    name: string;
    /**
     * Priority
     */
    priority: string;
    /**
     * Regulation Story
     */
    regulation_story: string;
    /**
     * Required Evidence Elements
     */
    required_evidence_elements: Array<RequiredEvidenceElement>;
    /**
     * Target Artifacts
     */
    target_artifacts: Array<string>;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    error: ApiErrorDetail;
};

/**
 * EvidenceArtifact
 */
export type EvidenceArtifact = {
    /**
     * Chunk Count
     */
    chunk_count: number;
    /**
     * Extension
     */
    extension: string;
    /**
     * Name
     */
    name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Environment
     */
    environment: string;
    /**
     * Openai Enabled
     */
    openai_enabled: boolean;
    /**
     * Openai Model
     */
    openai_model: string;
    /**
     * Phoenix Enabled
     */
    phoenix_enabled: boolean;
    /**
     * Phoenix Project Name
     */
    phoenix_project_name: string;
    /**
     * Service
     */
    service: string;
    /**
     * Status
     */
    status: string;
};

/**
 * PS3LinkedEvidenceView
 */
export type Ps3LinkedEvidenceView = {
    /**
     * Collection Date
     */
    collection_date: string;
    /**
     * Confidence Score
     */
    confidence_score: number;
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Flags
     */
    flags?: Array<string>;
    /**
     * Framework
     */
    framework: string;
    /**
     * Freshness Days
     */
    freshness_days: number;
    /**
     * Link Confidence
     */
    link_confidence: number;
    /**
     * Status
     */
    status?: string;
    /**
     * Type
     */
    type: string;
};

/**
 * PS3ReportResponse
 */
export type Ps3ReportResponse = {
    /**
     * Agent Trace
     */
    agent_trace?: Array<AgentTraceEntry>;
    /**
     * Disclaimer
     */
    disclaimer?: string;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Orphan Evidence Ids
     */
    orphan_evidence_ids?: Array<string>;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Requirements
     */
    requirements?: Array<RequirementReport>;
    summary: Ps3Summary;
};

/**
 * PS3Summary
 */
export type Ps3Summary = {
    /**
     * Auto Collected Pct
     */
    auto_collected_pct: number;
    /**
     * Compliant Count
     */
    compliant_count: number;
    /**
     * Coverage Pct
     */
    coverage_pct: number;
    /**
     * Exec Summary
     */
    exec_summary?: string;
    /**
     * Frameworks
     */
    frameworks?: Array<string>;
    /**
     * Freshness Pct
     */
    freshness_pct: number;
    /**
     * Gap Count
     */
    gap_count: number;
    /**
     * Linked Evidence Count
     */
    linked_evidence_count: number;
    /**
     * Orphan Count
     */
    orphan_count: number;
    /**
     * Overall Compliance Pct
     */
    overall_compliance_pct: number;
    /**
     * Partial Count
     */
    partial_count: number;
    /**
     * Total Evidence
     */
    total_evidence: number;
    /**
     * Total Requirements
     */
    total_requirements: number;
};

/**
 * RequiredEvidenceElement
 */
export type RequiredEvidenceElement = {
    /**
     * Critical
     */
    critical: boolean;
    /**
     * Description
     */
    description: string;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Negative Terms
     */
    negative_terms?: Array<string>;
    /**
     * Reviewer Gap
     */
    reviewer_gap: string;
    /**
     * Search Terms
     */
    search_terms: Array<string>;
};

/**
 * Requirement
 */
export type Requirement = {
    /**
     * Audit Frequency
     */
    audit_frequency?: string;
    /**
     * Compliance Mapping Raw
     */
    compliance_mapping_raw?: string;
    /**
     * Evidence Source
     */
    evidence_source?: string;
    /**
     * Frameworks
     */
    frameworks?: Array<string>;
    /**
     * Freshness Sla Days
     */
    freshness_sla_days?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Policy Id
     */
    policy_id: string;
    /**
     * Policy Name
     */
    policy_name: string;
    /**
     * Raw Text
     */
    raw_text: string;
    /**
     * Responsible
     */
    responsible?: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Text
     */
    text: string;
};

/**
 * RequirementCatalogResponse
 */
export type RequirementCatalogResponse = {
    /**
     * Count
     */
    count: number;
    /**
     * Requirements
     */
    requirements?: Array<Requirement>;
    /**
     * Source
     */
    source: string;
};

/**
 * RequirementReport
 */
export type RequirementReport = {
    /**
     * Audit Frequency
     */
    audit_frequency?: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Confidence Rationale
     */
    confidence_rationale?: string;
    /**
     * Frameworks
     */
    frameworks?: Array<string>;
    /**
     * Freshness Sla Days
     */
    freshness_sla_days: number;
    /**
     * Gaps
     */
    gaps?: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Linked Evidence
     */
    linked_evidence?: Array<Ps3LinkedEvidenceView>;
    /**
     * Name
     */
    name: string;
    /**
     * Narrative
     */
    narrative?: string;
    /**
     * Next Review Date
     */
    next_review_date?: string;
    /**
     * Policy Id
     */
    policy_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ToolTraceEntry
 */
export type ToolTraceEntry = {
    /**
     * Input
     */
    input: string;
    /**
     * Result
     */
    result: string;
    /**
     * Tool
     */
    tool: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AnalyzeEvidenceData = {
    body: BodyAnalyzeEvidence;
    path?: never;
    query?: never;
    url: '/analyze';
};

export type AnalyzeEvidenceErrors = {
    /**
     * Invalid evidence upload.
     */
    400: ErrorResponse;
    /**
     * Unsupported evidence file type.
     */
    415: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeEvidenceError = AnalyzeEvidenceErrors[keyof AnalyzeEvidenceErrors];

export type AnalyzeEvidenceResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResponse;
};

export type AnalyzeEvidenceResponse = AnalyzeEvidenceResponses[keyof AnalyzeEvidenceResponses];

export type StreamAnalyzeEvidenceData = {
    body: BodyStreamAnalyzeEvidence;
    path?: never;
    query?: never;
    url: '/analyze/stream';
};

export type StreamAnalyzeEvidenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamAnalyzeEvidenceError = StreamAnalyzeEvidenceErrors[keyof StreamAnalyzeEvidenceErrors];

export type StreamAnalyzeEvidenceResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetControlsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/controls';
};

export type GetControlsResponses = {
    /**
     * Successful Response
     */
    200: ControlCatalogResponse;
};

export type GetControlsResponse = GetControlsResponses[keyof GetControlsResponses];

export type GetDemoGoldenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/demo/golden';
};

export type GetDemoGoldenResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResponse;
};

export type GetDemoGoldenResponse = GetDemoGoldenResponses[keyof GetDemoGoldenResponses];

export type StreamDemoGoldenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/demo/golden/stream';
};

export type StreamDemoGoldenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetControlRegulatoryContextData = {
    body?: never;
    path: {
        /**
         * Control Id
         *
         * Control ID, e.g. FT-IAM-01
         */
        control_id: string;
    };
    query?: never;
    url: '/knowledge/context/{control_id}';
};

export type GetControlRegulatoryContextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetControlRegulatoryContextError = GetControlRegulatoryContextErrors[keyof GetControlRegulatoryContextErrors];

export type GetControlRegulatoryContextResponses = {
    /**
     * Response Getcontrolregulatorycontext
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetControlRegulatoryContextResponse = GetControlRegulatoryContextResponses[keyof GetControlRegulatoryContextResponses];

export type GetRulesByPriorityData = {
    body?: never;
    path: {
        /**
         * Priority
         *
         * Priority level, e.g. P1_Critical
         */
        priority: string;
    };
    query?: never;
    url: '/knowledge/priority/{priority}';
};

export type GetRulesByPriorityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRulesByPriorityError = GetRulesByPriorityErrors[keyof GetRulesByPriorityErrors];

export type GetRulesByPriorityResponses = {
    /**
     * Response Getrulesbypriority
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetRulesByPriorityResponse = GetRulesByPriorityResponses[keyof GetRulesByPriorityResponses];

export type GetControlGoverningRulesData = {
    body?: never;
    path: {
        /**
         * Control Id
         *
         * Control ID, e.g. FT-IAM-01
         */
        control_id: string;
    };
    query?: never;
    url: '/knowledge/rules/{control_id}';
};

export type GetControlGoverningRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetControlGoverningRulesError = GetControlGoverningRulesErrors[keyof GetControlGoverningRulesErrors];

export type GetControlGoverningRulesResponses = {
    /**
     * Response Getcontrolgoverningrules
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetControlGoverningRulesResponse = GetControlGoverningRulesResponses[keyof GetControlGoverningRulesResponses];

export type SearchRulesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/knowledge/search';
};

export type SearchRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchRulesError = SearchRulesErrors[keyof SearchRulesErrors];

export type SearchRulesResponses = {
    /**
     * Response Searchrules
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type SearchRulesResponse = SearchRulesResponses[keyof SearchRulesResponses];

export type GetKnowledgeGraphStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/knowledge/stats';
};

export type GetKnowledgeGraphStatsResponses = {
    /**
     * Response Getknowledgegraphstats
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetKnowledgeGraphStatsResponse = GetKnowledgeGraphStatsResponses[keyof GetKnowledgeGraphStatsResponses];

export type AnalyzePs3Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/analyze';
};

export type AnalyzePs3Responses = {
    /**
     * Successful Response
     */
    200: Ps3ReportResponse;
};

export type AnalyzePs3Response = AnalyzePs3Responses[keyof AnalyzePs3Responses];

export type StreamPs3AnalyzeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/analyze/stream';
};

export type StreamPs3AnalyzeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPs3ReportPdfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/report.pdf';
};

export type GetPs3ReportPdfResponses = {
    /**
     * PDF report
     */
    200: unknown;
};

export type GetPs3RequirementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/requirements';
};

export type GetPs3RequirementsResponses = {
    /**
     * Successful Response
     */
    200: RequirementCatalogResponse;
};

export type GetPs3RequirementsResponse = GetPs3RequirementsResponses[keyof GetPs3RequirementsResponses];

export type GetPs3RequirementData = {
    body?: never;
    path: {
        /**
         * Requirement Id
         */
        requirement_id: string;
    };
    query?: never;
    url: '/ps3/requirements/{requirement_id}';
};

export type GetPs3RequirementErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPs3RequirementError = GetPs3RequirementErrors[keyof GetPs3RequirementErrors];

export type GetPs3RequirementResponses = {
    /**
     * Successful Response
     */
    200: RequirementCatalogResponse;
};

export type GetPs3RequirementResponse = GetPs3RequirementResponses[keyof GetPs3RequirementResponses];
