// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AgentTraceEntry
 */
export type AgentTraceEntry = {
    /**
     * Agent
     */
    agent: string;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Summary
     */
    summary: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Environment
     */
    environment: string;
    /**
     * Openai Enabled
     */
    openai_enabled: boolean;
    /**
     * Openai Model
     */
    openai_model: string;
    /**
     * Phoenix Enabled
     */
    phoenix_enabled: boolean;
    /**
     * Phoenix Project Name
     */
    phoenix_project_name: string;
    /**
     * Service
     */
    service: string;
    /**
     * Status
     */
    status: string;
};

/**
 * PS3LinkedEvidenceView
 */
export type Ps3LinkedEvidenceView = {
    /**
     * Collection Date
     */
    collection_date: string;
    /**
     * Confidence Score
     */
    confidence_score: number;
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Flags
     */
    flags?: Array<string>;
    /**
     * Framework
     */
    framework: string;
    /**
     * Freshness Days
     */
    freshness_days: number;
    /**
     * Link Confidence
     */
    link_confidence: number;
    /**
     * Status
     */
    status?: string;
    /**
     * Type
     */
    type: string;
};

/**
 * PS3ReportResponse
 */
export type Ps3ReportResponse = {
    /**
     * Agent Trace
     */
    agent_trace?: Array<AgentTraceEntry>;
    /**
     * Disclaimer
     */
    disclaimer?: string;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Orphan Evidence Ids
     */
    orphan_evidence_ids?: Array<string>;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Requirements
     */
    requirements?: Array<RequirementReport>;
    summary: Ps3Summary;
};

/**
 * PS3Summary
 */
export type Ps3Summary = {
    /**
     * Auto Collected Pct
     */
    auto_collected_pct: number;
    /**
     * Compliant Count
     */
    compliant_count: number;
    /**
     * Coverage Pct
     */
    coverage_pct: number;
    /**
     * Exec Summary
     */
    exec_summary?: string;
    /**
     * Frameworks
     */
    frameworks?: Array<string>;
    /**
     * Freshness Pct
     */
    freshness_pct: number;
    /**
     * Gap Count
     */
    gap_count: number;
    /**
     * Linked Evidence Count
     */
    linked_evidence_count: number;
    /**
     * Orphan Count
     */
    orphan_count: number;
    /**
     * Overall Compliance Pct
     */
    overall_compliance_pct: number;
    /**
     * Partial Count
     */
    partial_count: number;
    /**
     * Total Evidence
     */
    total_evidence: number;
    /**
     * Total Requirements
     */
    total_requirements: number;
};

/**
 * Requirement
 */
export type Requirement = {
    /**
     * Audit Frequency
     */
    audit_frequency?: string;
    /**
     * Compliance Mapping Raw
     */
    compliance_mapping_raw?: string;
    /**
     * Evidence Source
     */
    evidence_source?: string;
    /**
     * Frameworks
     */
    frameworks?: Array<string>;
    /**
     * Freshness Sla Days
     */
    freshness_sla_days?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Policy Id
     */
    policy_id: string;
    /**
     * Policy Name
     */
    policy_name: string;
    /**
     * Raw Text
     */
    raw_text: string;
    /**
     * Responsible
     */
    responsible?: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Text
     */
    text: string;
};

/**
 * RequirementCatalogResponse
 */
export type RequirementCatalogResponse = {
    /**
     * Count
     */
    count: number;
    /**
     * Requirements
     */
    requirements?: Array<Requirement>;
    /**
     * Source
     */
    source: string;
};

/**
 * RequirementReport
 */
export type RequirementReport = {
    /**
     * Audit Frequency
     */
    audit_frequency?: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Confidence Rationale
     */
    confidence_rationale?: string;
    /**
     * Frameworks
     */
    frameworks?: Array<string>;
    /**
     * Freshness Sla Days
     */
    freshness_sla_days: number;
    /**
     * Gaps
     */
    gaps?: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Linked Evidence
     */
    linked_evidence?: Array<Ps3LinkedEvidenceView>;
    /**
     * Name
     */
    name: string;
    /**
     * Narrative
     */
    narrative?: string;
    /**
     * Next Review Date
     */
    next_review_date?: string;
    /**
     * Policy Id
     */
    policy_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type AnalyzePs3Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/analyze';
};

export type AnalyzePs3Responses = {
    /**
     * Successful Response
     */
    200: Ps3ReportResponse;
};

export type AnalyzePs3Response = AnalyzePs3Responses[keyof AnalyzePs3Responses];

export type StreamPs3AnalyzeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/analyze/stream';
};

export type StreamPs3AnalyzeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPs3ReportPdfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/report.pdf';
};

export type GetPs3ReportPdfResponses = {
    /**
     * PDF report
     */
    200: unknown;
};

export type GetPs3RequirementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ps3/requirements';
};

export type GetPs3RequirementsResponses = {
    /**
     * Successful Response
     */
    200: RequirementCatalogResponse;
};

export type GetPs3RequirementsResponse = GetPs3RequirementsResponses[keyof GetPs3RequirementsResponses];

export type GetPs3RequirementData = {
    body?: never;
    path: {
        /**
         * Requirement Id
         */
        requirement_id: string;
    };
    query?: never;
    url: '/ps3/requirements/{requirement_id}';
};

export type GetPs3RequirementErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPs3RequirementError = GetPs3RequirementErrors[keyof GetPs3RequirementErrors];

export type GetPs3RequirementResponses = {
    /**
     * Successful Response
     */
    200: RequirementCatalogResponse;
};

export type GetPs3RequirementResponse = GetPs3RequirementResponses[keyof GetPs3RequirementResponses];
